version: '3.8'

services: 
  backend: 
    container_name: backend
    image: node
    build: .
    ports:
      - 3000:3000
    environment:
    - PGUSER=anujr
    - PGPASSWORD=anujr
    - PGDATABASE=database_development
    - PGHOST=db # NAME OF THE SERVICE
    depends_on: # will wait for db service to finish
      - db
  db:
    container_name: db
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=anujr
      - POSTGRES_PASSWORD=anujr
      - POSTGRES_DB=database_development
    volumes:
      - pgdata:/var/lib/postgresql/data # stores data into local-dir

volumes:
  pgdata: {}
